development:
  adapter: postgresql
  encoding: utf8
  database: diffttt_development
  pool: 5
  host: localhost

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: diffttt_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: diffttt_production
  pool: 5